//
// Created by duazel on 16/04/2020.
//

#ifndef TESTJSON_INPUTJSON_H
#define TESTJSON_INPUTJSON_H

#include "json.hpp"
#include <string>
#include <vector>
#include "Individual.h"

using json = nlohmann::json;
using namespace aevol;

class IOJson {
 public:
  explicit IOJson(const std::string & filename);
  explicit IOJson(const std::string &param_in, const std::string &chromosome);
  explicit IOJson(ExpManager * exp_m);

  std::string strain_name();
  int max_indel_size() const;
  std::vector<Individual> & individuals();
  void write(const std::string &filename) const;
  void init();
  void load(ExpManager * exp_m, bool verbose = false,
                    char* chromosome = nullptr, int32_t lchromosome = 0,
                    char* plasmid = nullptr, int32_t lplasmid = 0);

  const std::string &getStrainName() const;
  void setStrainName(const std::string &strainName);
  const vector<Individual*> getIndividuals() const;
  void setIndividuals(const vector<Individual*> &individuals);
  void addIndividual(Individual *indiv, json gu_list);
  uint32_t getSeed() const;
  void setSeed(uint32_t seed);
  int getInitPopSize() const;
  void setInitPopSize(int initPopSize);
  int getWorldHeigth() const;
  void setWorldHeigth(int worldHeigth);
  int getWorldWidth() const;
  void setWorldWidth(int worldWidth);
  int getChromosomeInitialLength() const;
  void setChromosomeInitialLength(int chromosomeInitialLength);
  int getChromosomeMinLength() const;
  void setChromosomeMinLength(int chromosome_min_length_);
  int getFuzzyFlavor() const;
  void setFuzzyFlavor(int fuzzyFlavor);
  int getEnvSampling() const;
  void setEnvSampling(int envSampling);
  const list<Gaussian> &getEnvAddGaussian() const;
  void setEnvAddGaussian(const list<Gaussian> &envAddGaussian);
  double getMaxTriangleWidth() const;
  void setMaxTriangleWidth(double maxTriangleWidth);
  int getBackupStep() const;
  void setBackupStep(int backupStep);
  bool isRecordTree() const;
  void setRecordTree(bool recordTree);
  bool isMoreStats() const;
  void setMoreStats(bool moreStats);
  double getPointMutationRate() const;
  void setPointMutationRate(double pointMutationRate);
  double getSmallInsertionRate() const;
  void setSmallInsertionRate(double smallInsertionRate);
  double getSmallDeletionRate() const;
  void setSmallDeletionRate(double smallDeletionRate);
  int getMaxIndelSize() const;
  void setMaxIndelSize(int maxIndelSize);
  double getDuplicationRate() const;
  void setDuplicationRate(double duplicationRate);
  double getDeletionRate() const;
  void setDeletionRate(double deletionRate);
  double getTranslocationRate() const;
  void setTranslocationRate(double translocationRate);
  double getInversionRate() const;
  void setInversionRate(double inversionRate);
  bool isWithAlignments() const;
  void setWithAlignments(bool withAlignments);
  int getChromosomeMaxLength() const;
  void setChromosomeMaxLength(int chromosomeMaxLength);
  bool isAllowPlasmids() const;
  void setAllowPlasmids(bool allowPlasmids);

 private:
  AlignmentFunctionShape align_fun_shape_;
  int align_lin_max_;
  int align_lin_min_;
  int align_match_bonus_;
  int align_max_shift_;
  int align_mismatch_cost_;
  int align_sigm_lambda_;
  int align_sigm_mean_;
  int align_w_zone_h_len_;
  bool allow_plasmids_;
  int backup_step_;
  int big_backup_step_;
  int chromosome_initial_length_;
  int chromosome_minimal_length_;
  int chromosome_maximal_length_;
  bool compute_phen_contrib_by_GU_;
  bool delete_old_stats_;
  double deletion_rate_;
  double deletion_proportion_;
  double donor_cost_;
  int dump_step_;
  double duplication_proportion_;
  double duplication_rate_;
  list<Gaussian> env_add_gaussian_;
  int env_axis_nb_segments_;
  PhenotypicFeature *env_axis_features_;
  double *env_axis_segment_boundaries_;
  bool env_axis_separate_segments_;
  double env_noise_alpha_;
  int env_noise_sampling_log_;
  PhenotypicTargetNoiseMethod env_noise_method_;
  double env_noise_prob_;
  int env_noise_seed_;
  double env_noise_sigma_;
  int env_sampling_;
  PhenotypicTargetVariationMethod env_var_method_;
  double env_var_sigma_;
  int env_var_seed_;
  int env_var_tau_;
  std::string filename_;
  FitnessFunction fitness_function_;
  int fitness_function_x_;
  int fitness_function_y_;
  int fuzzy_flavor_;
  double HT_ins_rate_;
  double HT_repl_rate_;
  std::vector<Individual *> individuals_;
  int init_method_;
  int init_pop_size_;
  double inversion_proportion_;
  double inversion_rate_;
  json json_file_;
  int logs_;
  bool make_dumps_;
  int max_genome_length_;
  int max_indel_size_;
  double max_triangle_width_;
  int min_genome_length_;
  bool more_stats_;
  int mut_seed_;
  double neighbourhood_rate_;
  int32_t partial_mix_nb_permutations_;
  int plasmid_initial_gene_;
  int plasmid_initial_length_;
  int plasmid_maximal_length_;
  int plasmid_minimal_length_;
  double prob_plasmid_HT_;
  double point_mutation_rate_;
  std::shared_ptr<JumpingMT> prng_;
  double recipient_cost_;
  bool record_light_tree_;
  bool record_tree_;
  double repl_HT_detach_rate_;
  bool repl_HT_with_close_points_;
  double secretion_contrib_to_fitness_;
  double secretion_cost_;
  double secretion_degradation_prop_;
  double secretion_diffusion_prop_;
  double secretion_init_;
  uint32_t seed_;
  double selection_pressure_;
  SelectionScheme selection_scheme_;
  SelectionScope selection_scope_;
  int32_t selection_scope_x_;
  int32_t selection_scope_y_;
  double small_deletion_rate_;
  double small_insertion_rate_;
  int stats_;
  int stoch_seed_;
  std::string strain_name_;
  bool swap_GUs_;
  double translation_cost_;
  double translocation_proportion_;
  double translocation_rate_;
  int tree_step_;
  double tune_donor_ability_;
  double tune_recipient_ability_;
  bool with_alignments_;
  bool with_HT_;
  bool with_stochasticity_;
  bool with_secretion_;
  bool with_4pts_trans_;
  bool well_mixed;

 public:
  AlignmentFunctionShape getAlignFunShape() const;
  void setAlignFunShape(AlignmentFunctionShape alignFunShape);
  int getAlignLinMax() const;
  void setAlignLinMax(int alignLinMax);
  int getAlignLinMin() const;
  void setAlignLinMin(int alignLinMin);
  int getAlignMatchBonus() const;
  void setAlignMatchBonus(int alignMatchBonus);
  int getAlignMaxShift() const;
  void setAlignMaxShift(int alignMaxShift);
  int getAlignMismatchCost() const;
  void setAlignMismatchCost(int alignMismatchCost);
  int getAlignSigmLambda() const;
  void setAlignSigmLambda(int alignSigmLambda);
  int getAlignSigmMean() const;
  void setAlignSigmMean(int alignSigmMean);
  int getAlignWZoneHLen() const;
  void setAlignWZoneHLen(int alignWZoneHLen);
  int getBigBackupStep() const;
  void setBigBackupStep(int bigBackupStep);
  int getChromosomeMinimalLength() const;
  void setChromosomeMinimalLength(int chromosomeMinimalLength);
  int getChromosomeMaximalLength() const;
  void setChromosomeMaximalLength(int chromosomeMaximalLength);
  bool isComputePhenContribByGu() const;
  void setComputePhenContribByGu(bool computePhenContribByGu);
  bool isDeleteOldStats() const;
  void setDeleteOldStats(bool deleteOldStats);
  double getDeletionProportion() const;
  void setDeletionProportion(double deletionProportion);
  double getDonorCost() const;
  void setDonorCost(double donorCost);
  int getDumpStep() const;
  void setDumpStep(int dumpStep);
  double getDuplicationProportion() const;
  void setDuplicationProportion(double duplicationProportion);
  int getEnvAxisNbSegments() const;
  void setEnvAxisNbSegments(int envAxisNbSegments);
  PhenotypicFeature *getEnvAxisFeatures() const;
  void setEnvAxisFeatures(PhenotypicFeature *envAxisFeatures);
  double *getEnvAxisSegmentBoundaries() const;
  void setEnvAxisSegmentBoundaries(double *envAxisSegmentBoundaries);
  bool isEnvAxisSeparateSegments() const;
  void setEnvAxisSeparateSegments(bool envAxisSeparateSegments);
  double getEnvNoiseAlpha() const;
  void setEnvNoiseAlpha(double envNoiseAlpha);
  int getEnvNoiseSamplingLog() const;
  void setEnvNoiseSamplingLog(int envNoiseSamplingLog);
  PhenotypicTargetNoiseMethod getEnvNoiseMethod() const;
  void setEnvNoiseMethod(PhenotypicTargetNoiseMethod envNoiseMethod);
  double getEnvNoiseProb() const;
  void setEnvNoiseProb(double envNoiseProb);
  int getEnvNoiseSeed() const;
  void setEnvNoiseSeed(int envNoiseSeed);
  double getEnvNoiseSigma() const;
  void setEnvNoiseSigma(double envNoiseSigma);
  PhenotypicTargetVariationMethod getEnvVarMethod() const;
  void setEnvVarMethod(PhenotypicTargetVariationMethod envVarMethod);
  double getEnvVarSigma() const;
  void setEnvVarSigma(double envVarSigma);
  int getEnvVarSeed() const;
  void setEnvVarSeed(int envVarSeed);
  int getEnvVarTau() const;
  void setEnvVarTau(int envVarTau);
  const std::string &getFilename() const;
  void setFilename(const std::string &filename);
  FitnessFunction getFitnessFunction() const;
  void setFitnessFunction(FitnessFunction fitnessFunction);
  int getFitnessFunctionX() const;
  void setFitnessFunctionX(int fitnessFunctionX);
  int getFitnessFunctionY() const;
  void setFitnessFunctionY(int fitnessFunctionY);
  double getHtInsRate() const;
  void setHtInsRate(double htInsRate);
  double getHtReplRate() const;
  void setHtReplRate(double htReplRate);
  int getInitMethod() const;
  void setInitMethod(int initMethod);
  double getInversionProportion() const;
  void setInversionProportion(double inversionProportion);
  int getLogs() const;
  void setLogs(int logs);
  bool isMakeDumps() const;
  void setMakeDumps(bool makeDumps);
  int getMaxGenomeLength() const;
  void setMaxGenomeLength(int maxGenomeLength);
  int getMinGenomeLength() const;
  void setMinGenomeLength(int minGenomeLength);
  int getMutSeed() const;
  void setMutSeed(int mutSeed);
  double getNeighbourhoodRate() const;
  void setNeighbourhoodRate(double neighbourhoodRate);
  int32_t getPartialMixNbPermutations() const;
  void setPartialMixNbPermutations(int32_t partialMixNbPermutations);
  int getPlasmidInitialGene() const;
  void setPlasmidInitialGene(int plasmidInitialGene);
  int getPlasmidInitialLength() const;
  void setPlasmidInitialLength(int plasmidInitialLength);
  int getPlasmidMaximalLength() const;
  void setPlasmidMaximalLength(int plasmidMaximalLength);
  int getPlasmidMinimalLength() const;
  void setPlasmidMinimalLength(int plasmidMinimalLength);
  double getProbPlasmidHt() const;
  void setProbPlasmidHt(double probPlasmidHt);
  const std::shared_ptr<JumpingMT> &getPrng() const;
  void setPrng(const std::shared_ptr<JumpingMT> &prng);
  double getRecipientCost() const;
  void setRecipientCost(double recipientCost);
  bool isRecordLightTree() const;
  void setRecordLightTree(bool recordLightTree);
  double getReplHtDetachRate() const;
  void setReplHtDetachRate(double replHtDetachRate);
  bool isReplHtWithClosePoints() const;
  void setReplHtWithClosePoints(bool replHtWithClosePoints);
  double getSecretionContribToFitness() const;
  void setSecretionContribToFitness(double secretionContribToFitness);
  double getSecretionCost() const;
  void setSecretionCost(double secretionCost);
  double getSecretionDegradationProp() const;
  void setSecretionDegradationProp(double secretionDegradationProp);
  double getSecretionDiffusionProp() const;
  void setSecretionDiffusionProp(double secretionDiffusionProp);
  double getSecretionInit() const;
  void setSecretionInit(double secretionInit);
  double getSelectionPressure() const;
  void setSelectionPressure(double selectionPressure);
  const SelectionScheme getSelectionScheme() const;
  void setSelectionScheme(SelectionScheme selectionScheme);
  SelectionScope getSelectionScope() const;
  void setSelectionScope(SelectionScope selectionScope);
  int32_t getSelectionScopeX() const;
  void setSelectionScopeX(int32_t selectionScopeX);
  int32_t getSelectionScopeY() const;
  void setSelectionScopeY(int32_t selectionScopeY);
  int getStats() const;
  void setStats(int stats);
  int getStochSeed() const;
  void setStochSeed(int stochSeed);
  bool isSwapGUs() const;
  void setSwapGUs(bool swapGUs);
  double getTranslationCost() const;
  void setTranslationCost(double translationCost);
  double getTranslocationProportion() const;
  void setTranslocationProportion(double translocationProportion);
  int getTreeStep() const;
  void setTreeStep(int treeStep);
  double getTuneDonorAbility() const;
  void setTuneDonorAbility(double tuneDonorAbility);
  double getTuneRecipientAbility() const;
  void setTuneRecipientAbility(double tuneRecipientAbility);
  bool isWithHt() const;
  void setWithHt(bool withHt);
  bool isWithStochasticity() const;
  void setWithStochasticity(bool withStochasticity);
  bool isWithSecretion() const;
  void setWithSecretion(bool withSecretion);
  bool isWith4PtsTrans() const;
  void setWith4PtsTrans(bool with4PtsTrans);
  bool isWellMixed() const;
  void setWellMixed(bool wellMixed);
  std::string getIndividualSequence(int32_t index, int32_t gu) const;
  void setIndividualSequence(int32_t index, int32_t gu, const char* seq);
  int32_t getNbrIndividuals() const;
 private:
  int world_heigth_;
  int world_width_;
};

#endif // TESTJSON_INPUTJSON_H