./"test with man -l <file>
.TH AEVOL "1" "July 2014" "aevol 4.4" "User Manual"
.SH NAME
aevol \- an in silico experimental evolution platform
.SH SYNOPSIS
.B aevol_misc_lineage \-h
|
.B \-\-help
.br
.B aevol_misc_lineage \-V
|
.B \-\-version
.br
.B aevol_misc_lineage \fR[\fB\-i\fI INDEX\fR | \fB\-r\fI RANK\fR] \fR[\fB\-b\fI GENER1\fR] \fB\-e\fI GENER2
.SH DESCRIPTION
.B Aevol
is a simulation platform that allows one to let populations of digital organisms evolve in different conditions and study experimentally the mechanisms responsible for the structuration of the genome and the transcriptome.
.TP
.B aevol_misc_lineage
allows for the reconstruction of the lineage of a given individual. Requires the tree to have been recorded during evolution.
.SH OPTIONS
.TP
.B \-h, \-\-help
print help, then exit
.TP
.B \-V, \-\-version
print version number, then exit
.HP
.B \-i, \-\-index
.I  INDEX
.br
specify the index (ID in current generation) of the individual whose lineage is to be reconstructed
.HP
.B \-r, \-\-rank
.I  RANK
.br
specify the rank of the individual whose lineage is to be reconstructed
.HP
.B \-b, \-\-begin
.I  GENER
.br
specify the generation up to which the lineage is to be reconstructed
.HP
.B \-e, \-\-end
.I  GENER
.br
specify the generation of the individual whose lineage is to be reconstructed
.SH "SEE ALSO"
.B aevol_create, aevol_modify, aevol_propagate, aevol_run
